In [13]:
import torch
N, D_in, H1,H2,H3, D_out = 10 ,3 ,4,3,4 ,2
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

In [14]:
layer1 = torch.nn.Linear(D_in, H1)
layer2 = torch.nn.Linear(H1, H2)
layer3 = torch.nn.Linear(H2, H3, bias = False)
layer4 = torch.nn.Linear(H3, D_out)

loss_fn = torch.nn.MSELoss()

optimizer1 = torch.optim.SGD(layer1.parameters(), lr = 0.05, momentum = 0.9)
optimizer2 = torch.optim.SGD(layer2.parameters(), lr = 0.05, momentum = 0.9)
optimizer3 = torch.optim.SGD(layer3.parameters(), lr = 0.05, momentum = 0.9)
optimizer4 = torch.optim.SGD(layer4.parameters(), lr = 0.05, momentum = 0.9)


In [15]:
print(layer1.weight)
print(layer2.weight)
print(layer3.weight)
print(layer4.weight)

Parameter containing:
tensor([[-0.3311,  0.2519,  0.3068],
        [-0.3082,  0.3149, -0.4042],
        [-0.5510,  0.2228,  0.4530],
        [ 0.4059,  0.2195, -0.3058]], requires_grad=True)
Parameter containing:
tensor([[-0.3336, -0.4914, -0.3525, -0.1809],
        [ 0.2746,  0.0961,  0.2403, -0.2765],
        [-0.1256, -0.2266, -0.2378,  0.1720]], requires_grad=True)
Parameter containing:
tensor([[ 0.4106,  0.5603, -0.5586],
        [ 0.0385, -0.1680, -0.0208],
        [-0.0714, -0.1042,  0.0299],
        [ 0.4249, -0.3446,  0.4906]], requires_grad=True)
Parameter containing:
tensor([[ 0.0623,  0.3307,  0.4338, -0.1502],
        [ 0.0686, -0.3590, -0.4102, -0.1842]], requires_grad=True)


In [17]:
for i in range(5):
    print('step: {}'.format(i), end = '\r')
    print('before train , layer1.weight:',layer1.weight)
    
    #forward
    hidden1 = layer1.forward(x)
    
    hidden2 = layer2.forward(hidden1)
    hidden3 = layer3.forward(hidden2)
    y_pred = layer4.forward(hidden3)
    
    #computing the error
    loss = loss_fn(y_pred , y)
    print('loss:' , loss)
    
    # clear gradient of last step
    optimizer1.zero_grad()
    optimizer2.zero_grad()
    optimizer3.zero_grad()
    optimizer4.zero_grad()
    print("before backward, layer1.weight.grad:" , layer1.weight.grad)
    
    # backward
    loss.backward()
    print('after backward, layer1.weight.grad:' , layer1.weight.grad)
    
    #update weights
    optimizer1.step()
    optimizer2.step()
    optimizer3.step()
    optimizer4.step()
    print('after train, layer.weight:', layer1.weight)
    print(i, '-'*50)


before train , layer1.weight: Parameter containing:
tensor([[-0.3311,  0.2519,  0.3068],
        [-0.3082,  0.3149, -0.4042],
        [-0.5510,  0.2228,  0.4530],
        [ 0.4059,  0.2195, -0.3058]], requires_grad=True)
loss: tensor(1.2523, grad_fn=<MseLossBackward>)
before backward, layer1.weight.grad: None
after backward, layer1.weight.grad: tensor([[-0.0428, -0.0323, -0.0040],
        [-0.0381, -0.0295,  0.0014],
        [-0.0487, -0.0371, -0.0027],
        [ 0.0340,  0.0251,  0.0069]])
after train, layer.weight: Parameter containing:
tensor([[-0.3290,  0.2535,  0.3070],
        [-0.3063,  0.3163, -0.4042],
        [-0.5485,  0.2247,  0.4532],
        [ 0.4042,  0.2182, -0.3061]], requires_grad=True)
0 --------------------------------------------------
before train , layer1.weight: Parameter containing:
tensor([[-0.3290,  0.2535,  0.3070],
        [-0.3063,  0.3163, -0.4042],
        [-0.5485,  0.2247,  0.4532],
        [ 0.4042,  0.2182, -0.3061]], requires_grad=True)
loss: tensor